/* BANCO PRINCIPAL */

CREATE DATABASE TASK;

USE TASK;

CREATE TABLE TASK(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	TITLE VARCHAR(50),
	DESCRIPTION VARCHAR(50),
	DATE VARCHAR(30),
	STATUS VARCHAR(30),
	IDLOCAL VARCHAR(10)
);

/* BANCO DE BACKUP */

CREATE DATABASE BACKUP_TASK;

USE BACKUP_TASK;


CREATE TABLE BKP_TASK(
	ID_BKP INT PRIMARY KEY AUTO_INCREMENT,
	ID INT,
	TITLE VARCHAR(50),
	DESCRIPTION VARCHAR(50),
	DATE VARCHAR(30),
	STATUS VARCHAR(30),
	IDLOCAL VARCHAR(10)
);


USE TASK;

/* CRIANDO A TRIGGER PARA ALIMENTAR A TABELA DE BACKUP */

DELIMITER $

CREATE TRIGGER BACKUP_TASK
BEFORE INSERT ON TASK
FOR EACH ROW

BEGIN
	
	INSERT INTO BACKUP_TASK.BKP_TASK VALUES (NULL, NEW.ID, NEW.TITLE, NEW.DESCRIPTION, NEW.STATUS, NEW.IDLOCAL);

END
$

DELIMITER ;

